"""Phase 8 — price snapshot dump for Dataview dashboards (D-08).

Writes ``dashboards/_data/prices.md`` every ingest cycle. The file is a
*derived cache* (regeneratable from DB), so it MUST be gitignored — see
``.gitignore`` (Pitfall 6).

Frontmatter:
- ``as_of``: last trading day, ISO date.
- ``type``: ``derived_prices`` (Dataview filter discriminator).
- ``prices``: inline dict ``{ticker: latest_close}`` so Dataview can join
  this file's frontmatter against ``notes/private/portfolio.md`` (D-08).

Body: ticker × name × latest_close markdown table (human-readable mirror).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

import yaml
from sqlalchemy import text
from sqlalchemy.engine import Engine

HEADER = "<!-- AUTO-GENERATED by src/ingest/price_snapshot.py — DO NOT EDIT -->\n\n"


@dataclass
class PriceRow:
    ticker: str
    name: str
    latest_close: int | None
    prices_30d: list[tuple[date, int]]  # for hub_builder reuse


def render_prices_md(rows: list[PriceRow], as_of: date) -> str:
    """Pure function. Returns the full markdown content for prices.md.

    No datetime.now() — output is fully determined by ``rows`` + ``as_of``.
    """
    prices_inline: dict[str, int | None] = {r.ticker: r.latest_close for r in rows}
    fm = {
        "as_of": as_of.isoformat(),
        "type": "derived_prices",
        "prices": prices_inline,
    }
    body_lines = [
        "",
        "## Latest Close",
        "",
        "| Ticker | Name | Close |",
        "|---|---|---|",
    ]
    for r in rows:
        close_str = str(r.latest_close) if r.latest_close is not None else "—"
        body_lines.append(f"| {r.ticker} | {r.name} | {close_str} |")
    yaml_block = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True)
    return "---\n" + yaml_block + "---\n" + HEADER + "\n".join(body_lines) + "\n"


def collect_prices(engine: Engine) -> tuple[list[PriceRow], date | None]:
    """Query KRX-derived rows from DB. Returns ([], None) if no data.

    Phase 8 minimal implementation: SELECT one row per ticker from
    ``documents`` where ``source = 'krx'``, latest by ``first_seen_at``.
    The ``latest_close`` is parsed from the document body — Phase 4 KRX
    writer guarantees a frontmatter zone with the close — but the price
    isn't yet in a typed column. Until that lands, this stub returns
    ``([], None)``; tests inject via ``patch``.
    """
    if engine is None:
        return [], None
    rows: list[PriceRow] = []
    as_of: date | None = None
    with engine.begin() as conn:
        result = conn.execute(
            text(
                "SELECT corp_code, MAX(first_seen_at)::date AS d "
                "FROM documents WHERE source = 'krx' GROUP BY corp_code"
            )
        ).all()
        for cc, d in result:
            if as_of is None or (d is not None and d > as_of):
                as_of = d
            rows.append(
                PriceRow(
                    ticker=str(cc)[:6] if cc else "",
                    name="",
                    latest_close=None,
                    prices_30d=[],
                )
            )
    return rows, as_of


def run(engine: Engine | None, repo_root: Path) -> bool:
    """Entry from worker post-cycle. Returns True iff file written/changed."""
    rows, as_of = collect_prices(engine)
    if as_of is None:
        return False
    body = render_prices_md(rows, as_of)
    out = repo_root / "dashboards" / "_data" / "prices.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists() and out.read_text(encoding="utf-8") == body:
        return False
    tmp = out.with_suffix(out.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(out)
    return True
